__base__: '../runtime.yml'

# train
tain_dataloader:
  dataset:
    return_masks: False
    remap_mscoco_category: ~
    transforms: 
      type: Compose
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBox, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: RandomShortestSize, min_size: 640, max_size: 800}
        - {type: Pad, padding_mode: 'constant', fill: [114, 114, 114]}
        - {type: Resize, size: [640, 640]}
        - {type: ToImageTensor}
        - {type: ConvertDtype}
        - {type: SanitizeBoundingBox, min_size: 1}
        - {type: ConvertBox, out_fmt: 'cxcywh', normalize: True}

  shuffle: True
  batch_size: 6
  num_workers: 4
  persistent_workers: False
  pin_memory: True
  drop_last: True
  collate_fn: default_collate_fn


# val
val_dataloader:
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [640, 640]}
        - {type: ToImageTensor}
        - {type: ConvertDtype}
  shuffle: False
  batch_size: 6
  num_workers: 4
  persistent_workers: False
  pin_memory: True
  drop_last: False
  collate_fn: default_collate_fn